const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94716682532"
const SESSION_ID = "PRABATH-MD~cdQmFTbC#mEeftxPLjiz6rln7dEMm_XPoYbKloTL0p-ecp2zflEc"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
